-- PixelForge Games - creación del esquema Oracle
-- Ejecutar en SQL*Plus con una cuenta DBA: @database/create_user.sql
SET SERVEROUTPUT ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = ORCLPDB;

ACCEPT schema_password CHAR PROMPT 'Contraseña para PIXELFORGE_APP: ' HIDE

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'PIXELFORGE_APP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER PIXELFORGE_APP IDENTIFIED BY "&schema_password"';
        DBMS_OUTPUT.PUT_LINE('Usuario PIXELFORGE_APP creado.');
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER PIXELFORGE_APP IDENTIFIED BY "&schema_password" ACCOUNT UNLOCK';
        DBMS_OUTPUT.PUT_LINE('Usuario PIXELFORGE_APP actualizado.');
    END IF;
END;
/

ALTER USER PIXELFORGE_APP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER,
      CREATE VIEW, CREATE PROCEDURE TO PIXELFORGE_APP;

PROMPT Esquema PIXELFORGE_APP listo para ejecutar migraciones.
EXIT

